name: Build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Checkout wireproxy
      uses: actions/checkout@v2
    - name: Build wireproxy
      run: go build ./cmd/wireproxy

